FROM jenkins/jenkins:lts

USER root

# ------------------------------------------------
# Install Required Base Packages
# ------------------------------------------------

RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    wget \
    apt-transport-https \
    ca-certificates \
    gnupg \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*

# ------------------------------------------------
# Install Docker CLI
# ------------------------------------------------

RUN mkdir -p /etc/apt/keyrings

RUN curl -fsSL https://download.docker.com/linux/debian/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" \
    | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update && apt-get install -y docker-ce-cli

# ------------------------------------------------
# Install AWS CLI v2
# ------------------------------------------------

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" \
    -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf aws awscliv2.zip

# ------------------------------------------------
# Install kubectl
# ------------------------------------------------

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl \
    && rm kubectl

# ------------------------------------------------
# Install Helm
# ------------------------------------------------

RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# ------------------------------------------------
# Install Node.js 18
# ------------------------------------------------

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# ------------------------------------------------
# Docker Group Permissions
# IMPORTANT:
# Match Docker GID with EC2 host
# Run on EC2 host:
# getent group docker
# Example:
# docker:x:992:
# ------------------------------------------------

RUN groupadd -g 992 docker || true

RUN usermod -aG docker jenkins

# ------------------------------------------------
# Verify Installations
# ------------------------------------------------

RUN docker --version

RUN aws --version

RUN kubectl version --client

RUN helm version

RUN node --version

ENV AWS_PAGER=""

# ------------------------------------------------
# Switch Back to Jenkins User
# ------------------------------------------------

USER jenkins